[package]
name = "rust-56-cody-client"
version = "0.1.0"
edition = "2021"
authors = ["kiraum <tfgoncalves@xpto.it>"]

[dependencies]
futures = "0.3"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "1.0", features = ["full"] }
