# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "My eval"

prompts:
  - file://prompt.py:code_reviewer

providers:
  - "exec: node complete.js claude-3.5-sonnet"
  # - "exec: node complete.js gemini-1.5-pro"
  - "exec: node complete.js gpt-4o"

tests:
  - vars:
      dir: test-dir/typescript
  - vars:
      dir: test-dir/java

